// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo3KvO0suMhMCwVEcEPLpHWT7DLoDVgJk',
    appId: '1:997784356755:web:56a3c66a47b8fa84a00a66',
    messagingSenderId: '997784356755',
    projectId: 'newapp-d9a2a',
    authDomain: 'newapp-d9a2a.firebaseapp.com',
    storageBucket: 'newapp-d9a2a.appspot.com',
    measurementId: 'G-2WTKP9E971',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPgg-wVxYhJa6pN4RyZSSCToDioUwqqY',
    appId: '1:997784356755:android:152837d2568d3919a00a66',
    messagingSenderId: '997784356755',
    projectId: 'newapp-d9a2a',
    storageBucket: 'newapp-d9a2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNV6zaka21YLKr-nzhNx8MhNqnA5Fc9Lc',
    appId: '1:997784356755:ios:97b4a243f018386da00a66',
    messagingSenderId: '997784356755',
    projectId: 'newapp-d9a2a',
    storageBucket: 'newapp-d9a2a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNV6zaka21YLKr-nzhNx8MhNqnA5Fc9Lc',
    appId: '1:997784356755:ios:97b4a243f018386da00a66',
    messagingSenderId: '997784356755',
    projectId: 'newapp-d9a2a',
    storageBucket: 'newapp-d9a2a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo3KvO0suMhMCwVEcEPLpHWT7DLoDVgJk',
    appId: '1:997784356755:web:e8b49d21445965d5a00a66',
    messagingSenderId: '997784356755',
    projectId: 'newapp-d9a2a',
    authDomain: 'newapp-d9a2a.firebaseapp.com',
    storageBucket: 'newapp-d9a2a.appspot.com',
    measurementId: 'G-2L87C2C8LQ',
  );
}
